name: Output information
on: workflow_dispatch
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github context
        run: |
          echo "GITHUB_WORKFLOW=${{ github.workflow }}"
          echo "${{toJson(github)}}"
